### ISSUE TITLE
Rename terraboard; name already in use for Terraform UI

### ISSUE THREAD

**Issue by mbarrien** [Ghost---Shadow/terraboard#1]
I strongly suggest naming this to avoid naming conflicts with another Terraform UI, <http://github.com/camptocamp/terraboard>. This current naming will cause a lot of confusion.

**Comment by Ghost---Shadow** [comment]
Can you suggest a new name?
How about terraformboard?
The idea is similar to tensorboard, I want want to keep the word "board" in it.
